# Generated by Django 5.1 on 2024-08-17 18:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ticket_type', models.CharField(max_length=300)),
                ('student', models.BooleanField(default=True)),
                ('indian', models.BooleanField(default=True)),
                ('paid', models.BooleanField(default=False)),
                ('confirm', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(122)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
