# Generated by Django 5.1 on 2024-08-22 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='total_cost',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
